server:
  # Specify the port that runs the Data Center System
  port: 8085
mysql:
  # Specify the IP address, port number and the name of your database
  write_url: jdbc:mysql://database-IP:port/db_name?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&allowMultiQueries=true&useSSL=false
  # Enter the login name of the database
  write_username: db_username
  # Enter the password
  write_password: db_password
  # Specity the IP address, port number and the name of your database
  read_url: jdbc:mysql://database-IP:port/db_name?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&allowMultiQueries=true&useSSL=false
  # Enter the login name of the database
  read_username: db_username
  # Enter the password
  read_password: db_password

chain:
  # Default Node's JSON-RPC interface (--http.port) of Spartan-I Chain
  nodeRpcAddress: "http://node-IP:node-rpc-port"
  # Default chain's network ID, do not change this parameter
  chainId: 9090
  # Query the transaction pool's waiting time: millisecond, recommended 1.5 seconds
  txPoolSleep: 1500
  # Change the path of the Keystore file to a designated directory
  walletFilePath: "your-directory/wallet"
  # The system will parse events from all blocks after this block height. This number is recommended to be set as the latest block height of the Default Chain before the Data Center System started. For example: blockHeight: 270441
  # You can get the block height from the blockchain explorer: https://spartanone.bsn.foundation
  blockHeight: 1683752
  
kongGateWayConfig:
  username: admin
  password: abc123
  userAccessKeyUrl: /gateway/api/v0/accessKey/save
  userDefaultReqConfig: /gateway/api/v0/accessKey/defaultConfig